# Numpy

Numpy is one of the most important libraries of Python, we're going
to see why is this and also examples of how to use it and what is it used for.

It let's you realize maths with numeric arrays at high speed, instead 
the normal lists of Python; also it has a really wide set of tools to make
operations eficiently and with less code.

Also, most of Python's libraries are based on Numpy, for example: Pandas.

In [4]:
# You use the alias "np" to name the library
import numpy as np
"""
We create a "np" array of range 1 (one dimension) with the method "array()",
the numbers between square brackets are rows from the array and each number separated
with commas are the columns.
"""
an_array = np.array([7, 77, 777])
# This variable is a type "numpy.ndarray", n (number) of "d" (dimensions) of this array.
print(type(an_array))

<class 'numpy.ndarray'>


In [15]:
# We search what's the data type of the array's shape object and then we print the shape of the array.
print (type(an_array.shape))
# Since it's only 1 dimension you will only see a number meaning how many columns it has.
print(an_array.shape)
# Now this is how you create a two dimensions array, and each dimension should have the same lenght.
a_two_dimension_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:", a_two_dimension_array.shape)
print(a_two_dimension_array)

<class 'tuple'>
(4,)
Shape of the array: (2, 3)
[[1 2 3]
 [4 5 6]]


In [17]:
# How to access those variables
print(an_array[0])
print(an_array[1])
print(an_array[2])
an_array[2] = 200
print(an_array[2])

7
77
777
200


# How to create a multidimensional array

In [18]:
multidimensional_array = np.array([[11, 12, 13], [22, 23, 24], [35, 36, 37]])
print("Shape of this array is:",multidimensional_array.shape)

Shape of this array is:  (3, 3)


In [20]:
print("This is how I access a value of this two-dimension array:",multidimensional_array[2, 0])
print("This is how I print the full array")
print(multidimensional_array)

This is how I access a value of this two-dimension array: 35
This is how I print the full array
[[11 12 13]
 [22 23 24]
 [35 36 37]]


$ I^{3 \times 3} =
\left( \begin{array}{cccc}
 11 & 12 & 13 \\
 22 & 23 & 24 \\
 35 & 36 & 37 \\
\end{array} \right) $

# Multiple ways of creating nd arrays

In [21]:
#How to create a full-zero array, with the method "zeros()"
i1 = np.zeros((1080, 1920))
print(i1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
"""
This method will fill all the numbers from an array with the method "full()"; first
argument means the dimensions of the array and the second the number you want to fill in in each position
"""
i2 = np.full((2,2), 9.1)
print(i2)