# Numpy

Numpy is one of the most important libraries of Python, we're going
to see why is this and also examples of how to use it and what is it used for.

It let's you realize maths with numeric arrays at high speed, instead 
the normal lists of Python; also it has a really wide set of tools to make
operations eficiently and with less code.

Also, most of Python's libraries are based on Numpy, for example: Pandas.

In [4]:
# You use the alias "np" to name the library
import numpy as np
"""
We create a "np" array of range 1 (one dimension) with the method "array()",
the numbers between square brackets are rows from the array and each number separated
with commas are the columns.
"""
an_array = np.array([7, 77, 777])
# This variable is a type "numpy.ndarray", n (number) of "d" (dimensions) of this array.
print(type(an_array))

<class 'numpy.ndarray'>


In [15]:
# We search what's the data type of the array's shape object and then we print the shape of the array.
print (type(an_array.shape))
# Since it's only 1 dimension you will only see a number meaning how many columns it has.
print(an_array.shape)
# Now this is how you create a two dimensions array, and each dimension should have the same lenght.
a_two_dimension_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:", a_two_dimension_array.shape)
print(a_two_dimension_array)

<class 'tuple'>
(4,)
Shape of the array: (2, 3)
[[1 2 3]
 [4 5 6]]


In [17]:
# How to access those variables
print(an_array[0])
print(an_array[1])
print(an_array[2])
an_array[2] = 200
print(an_array[2])

7
77
777
200


# How to create a multidimensional array

In [18]:
multidimensional_array = np.array([[11, 12, 13], [22, 23, 24], [35, 36, 37]])
print("Shape of this array is:",multidimensional_array.shape)

Shape of this array is:  (3, 3)


In [20]:
print("This is how I access a value of this two-dimension array:",multidimensional_array[2, 0])
print("This is how I print the full array")
print(multidimensional_array)

This is how I access a value of this two-dimension array: 35
This is how I print the full array
[[11 12 13]
 [22 23 24]
 [35 36 37]]


$ I^{3 \times 3} =
\left( \begin{array}{cccc}
 11 & 12 & 13 \\
 22 & 23 & 24 \\
 35 & 36 & 37 \\
\end{array} \right) $

# Multiple ways of creating nd arrays

In [25]:
#How to create a full-zero array, with the method "zeros()"
i1 = np.zeros((1080, 1920))
print(i1)
# How can we add a dimension color? With another dimension with colours (red, green, blue, alpha, ultraviolet)
i1 = np.zeros((1080, 1920, 5))
print (i1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 ...

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [22]:
"""
This method will fill all the numbers from an array with the method "full()"; first
argument means the dimensions of the array and the second the number you want to fill in in each position
"""
i2 = np.full((2,2), 9.1)
print(i2)

[[9.1 9.1]
 [9.1 9.1]]


In [23]:
# The method "eye()" creates an identity matrix
i3 = np.eye(7,7)
print(i3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [24]:
# This method creates an array full of ones
i4 = np.ones((10,7,2))
print (i4)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [26]:
"""
We can also create an array full of random floats between 0 and 1; we're using the method
inside numpy's class "random" called also "random()".
"""
i5 = np.random.random((5,5))
print(i5)

[[0.69388803 0.43459109 0.95679906 0.90415641 0.55813781]
 [0.32745411 0.20352935 0.08898136 0.17761109 0.1603336 ]
 [0.46054914 0.93561055 0.83772828 0.88674495 0.0495275 ]
 [0.80420444 0.74649425 0.4199305  0.16697614 0.06411974]
 [0.35098443 0.67965012 0.85275943 0.68997237 0.88733409]]


# Array with indexes
Sometimes preparing a series of indexes in an array is useful to utilize them to operate other arrays

In [28]:
#Let's create a new two-dimensional array
array_a = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
print(array_a)
print(array_a.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
(4, 3)


In [29]:
# Let's create 2 arrays with integer numbers that we'll use as indexes
columns = np.array([0, 1, 2, 0])
# The method "arange()" generates a consecutive sequence of numbers from 0 to n-1 (in this example, 3)
rows = np.arange(4)
print("We choose this indexes for rows:",rows)
print("We choose this indexes for columns:",columns)

We choose this indexes for rows: [0 1 2 3]
We choose this indexes for columns: [0 1 2 0]


In [30]:
# We can print the indexes by columns from both arrays
for row,col in zip(rows,columns):
    print("(",row,",",col,")")

( 0 , 0 )
( 1 , 1 )
( 2 , 2 )
( 3 , 0 )


In [31]:
# So now to choose an element from a row we'll do it this way
print("The values contained in the indexes are:",array_a[rows, columns])

The values contained in the indexes are: [11 22 33 41]


In [34]:
# Let's operate with the selected values
print(array_a)
array_a[rows, columns] += 1000
print("\nNew array:\n")
print(array_a)

[[2011   12   13]
 [  21 2022   23]
 [  31   32 2033]
 [2041   42   43]]

New array:

[[3011   12   13]
 [  21 3022   23]
 [  31   32 3033]
 [3041   42   43]]


# Indexed boolean
Indexed boolean to chage elements

In [39]:
# We'll create an array of 3x2 dimensions
array_b = np.array([[11,12], [21,22], [31, 32]])
print(array_b)
print("_________")
print(array_b.shape)

[[11 12]
 [21 22]
 [31 32]]
_________
(3, 2)


In [40]:
# Creating a filter is really easy with Numpy
filter = (array_b > 15)
print(filter)
# Then we can have a new array with the filtered numbers
filtered = array_b[filter]
print(filtered)

[[False False]
 [ True  True]
 [ True  True]]


In [45]:
# This way you don't have to create the filter first and then apply it, we can do it in the same line of code
print(array_b[(array_b % 2 == 0)])

[12 22 32]


##### The principal use of this type of filters is to modify the values inside of the array that meet certain criteria

In [48]:
print("Full array:\n",array_b)
print("\nFiltered array:\n", array_b[array_b % 2 == 0])
array_b[array_b % 2 == 0] += 1000
print("\nArray after changing only the filtered values:\n",array_b)

Full array:
 [[  11 2012]
 [  21 2022]
 [  31 2032]]

Filtered array:
 [2012 2022 2032]

Array after changing only the filtered values:
 [[  11 3012]
 [  21 3022]
 [  31 3032]]
